# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathematics.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mathematics.proto\x12\x0bmathematics\"-\n\x0fRequestIntegers\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"!\n\x0fResponseInteger\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1f\n\rResponseFloat\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\xc0\x02\n\x0bMathematics\x12K\n\x0bSumIntegers\x12\x1c.mathematics.RequestIntegers\x1a\x1c.mathematics.ResponseInteger\"\x00\x12K\n\x0bSubIntegers\x12\x1c.mathematics.RequestIntegers\x1a\x1c.mathematics.ResponseInteger\"\x00\x12L\n\x0cMultIntegers\x12\x1c.mathematics.RequestIntegers\x1a\x1c.mathematics.ResponseInteger\"\x00\x12I\n\x0b\x44\x65vIntegers\x12\x1c.mathematics.RequestIntegers\x1a\x1a.mathematics.ResponseFloat\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathematics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTINTEGERS']._serialized_start=34
  _globals['_REQUESTINTEGERS']._serialized_end=79
  _globals['_RESPONSEINTEGER']._serialized_start=81
  _globals['_RESPONSEINTEGER']._serialized_end=114
  _globals['_RESPONSEFLOAT']._serialized_start=116
  _globals['_RESPONSEFLOAT']._serialized_end=147
  _globals['_MATHEMATICS']._serialized_start=150
  _globals['_MATHEMATICS']._serialized_end=470
# @@protoc_insertion_point(module_scope)
